language: python
python:
    - "2.7"
env:
    global:
        MPLBACKEND="agg"
cache: pip
install:
    - pip install -r requirements.txt
script: python -m unittest discover
branches:
  only:
    - master
